service: serverless-rest-api-codebase

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: ap-southeast-1
  environment:
    DYNAMODB_TABLE: Todo
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  create:
    handler: handle.create
    events:
      - http:
          path: todos
          integration: lambda
          method: post
          cors: true

  list:
    handler: handle.list
    events:
      - http:
          path: todos
          method: get
          integration: lambda
          cors: true

  get:
    handler: handle.get
    events:
      - http:
          path: todos/{id}
          integration: lambda
          method: get
          cors: true

  update:
    handler: handle.update
    events:
      - http:
          path: todos/{id}
          integration: lambda
          method: put
          cors: true

  delete:
    handler: handle.delete
    events:
      - http:
          path: todos/{id}
          integration: lambda
          method: delete
          cors: true
